### ISSUE TITLE
About Search

### ISSUE THREAD

**Issue by LianShuaiLong** [JaminFong/DenseNAS#12]
您好，有个问题想请教一下，DenseNAS在search阶段只用到了100类数据，而在retrain阶段使用了全部的1000类，这样设置的原因是因为希望search阶段很快的执行，我这样理解对么？

**Comment by JaminFong** [comment]
您好，是这样的。实验中只用100类同样能取得较好的搜索结果，并能有效减小搜索代价。

**Comment by LianShuaiLong** [comment]
> 您好，是这样的。实验中只用100类同样能取得较好的搜索结果，并能有效减小搜索代价。

感谢您的及时回复，您的100类是随机选取的么？

**Comment by JaminFong** [comment]
实验中选了前100类，也可以随机选取。

**Comment by LianShuaiLong** [comment]
> 实验中选了前100类，也可以随机选取。

好的谢谢您，第一次接触AutoDL,问题有点多，麻烦您了

**Comment by JaminFong** [comment]
不客气。
