### ISSUE TITLE
some questions about  search_space_mbv2.py

### ISSUE THREAD

**Issue by LianShuaiLong** [JaminFong/DenseNAS#14]
您好，有一个问题请教一下，为什么在search_space_mbv2里面Network类没有定义forward函数？没有forward函数，network里面不同的block之间是怎么衔接起来的呢？

**Comment by JaminFong** [comment]
search_space只负责定义所有的modules，实际forward在`models/dropped_model.py`中执行。
https://github.com/JaminFong/DenseNAS/blob/e479206f9d73808d4167c669bb1d045a73b6f470/run_apis/optimizer.py#L67

**Comment by LianShuaiLong** [comment]
> 义所有的modules，实

好的，找到了，谢谢您
