### ISSUE TITLE
关于DenseNAS中stage的疑问

### ISSUE THREAD

**Issue by LianShuaiLong** [JaminFong/DenseNAS#15]
您好，有一个问题想请教一下，DenseNAS中的stage与Mobilenetv2中的stage貌似不是对应的？
mobilenetv2中由7个stage，19个residual block，与论文中的Figure4所展示出来的不一样

您论文里面的mobilenetv2-based是网络结构中的operation包含MBconv的意思么？如果是的话，DenseNAS中的stage数是怎么确定的？

**Comment by JaminFong** [comment]
- 您提到的stage在DenseNAS论文中被定义为block，block的数量是通过搜索block之间最佳路径来确定的，这也是为什么要设计densely connected search space来获得更高灵活度的搜索。
- 论文里面的mobilenetv2-based是网络结构中的operation基于MBconv的意思

**Comment by LianShuaiLong** [comment]
> * 您提到的stage在DenseNAS论文中被定义为block，block的数量是通过搜索block之间最佳路径来确定的，这也是为什么要设计densely connected search space来获得更高灵活度的搜索。
> * 论文里面的mobilenetv2-based是网络结构中的operation基于MBconv的意思

您好，还有一个问题想请教一下，您Fig4里面的mobilenetv2貌似跟原本的mobilenetv2网络结构不一样？

**Comment by JaminFong** [comment]
哪里不一样呢？

**Comment by LianShuaiLong** [comment]
> 哪里不一样呢？

哦哦，我看错了，不好意思。。。。
