### ISSUE TITLE
retrain阶段的net_config问题

### ISSUE THREAD

**Issue by LianShuaiLong** [JaminFong/DenseNAS#16]
您好，有一个问题想请教一下，我在跑完search阶段，准备运行retrain，请问运行时候的net_config文件是再第一个阶段自动生成的么？我的output里面只有excel_record，weights_*.pt这些文件，并没有找到net_config文件，请问是我search阶段出现什么问题了么？

**Comment by JaminFong** [comment]
Please refer to 
> https://github.com/JaminFong/FNA/issues/3

**Comment by LianShuaiLong** [comment]
> Please refer to
> 
> > [JaminFong/FNA#3](https://github.com/JaminFong/FNA/issues/3)

thanks
