### ISSUE TITLE
Some questions about the search stage

### ISSUE THREAD

**Issue by Lorien2027** [JaminFong/DenseNAS#17]
Hi, I am currently trying to reproduce the search process for the default configuration. Could you please provide the following information:
1) The names of 100 classes and, if possible, the full names of the files used in train and validation splits, since their obtaining in the code is platform-dependent
2) The specific version of pytorch used, since in the version 1.6.0 there is a bug related to DataParallel and replication of architecture parameters to other gpus (for example, https://github.com/pytorch/pytorch/issues/36035). In this regard, the search stage does not work in multi-gpu enviroment
3) Log files (log.txt) for search and train stages with default config file (if I understand correctly it matches DenseNAS-C model)

**Comment by JaminFong** [comment]
Hi, please fetch the files you mentioned from [google_drive_url](https://drive.google.com/drive/folders/1FJFjjZxWx2N4Zg_-hEvFnX0NsEHTB5aU?usp=sharing).
1. For the complete file names, please refer to `train_datalist` and `val_datalist`
2. We have tested our code on pytorch 1.0 - 1.2. Have a try if needed.
3. The search logs include `search_log_1.txt` and `search_log_2.txt`, where `search_log_2.txt` resumes from `search_log_1.txt` to adjust the lamda value of Eq. (8) defined in the paper.

**Comment by Lorien2027** [comment]
Thanks for your reply.
