### ISSUE TITLE
architecture derived problem

### ISSUE THREAD

**Issue by mileswyn** [JaminFong/DenseNAS#18]
Hello, thanks for your works.
When I test your code, I found a problem that confuses me a lot.
When I run the search relevant scripts, I found that the super_model tends to choose the small kernel&ratio operation at final in class 'ArchGenerate'. I wonder if I do sth wrong during my test. Here are some parts of log files which prove my problems.

####################
11/19 11:16:15 Derived arch: 
[[16, 16], 'mbconv_k3_t1', [], 0, 1]|
[[16, 24], 'mbconv_k3_t3', ['mbconv_k3_t3', 'mbconv_k7_t6'], 2, 2]|
[[24, 48], 'mbconv_k7_t6', ['mbconv_k7_t6'], 1, 2]|
[[48, 72], 'mbconv_k5_t6', ['mbconv_k5_t3', 'mbconv_k7_t6', 'mbconv_k7_t6'], 3, 2]|
[[72, 128], 'mbconv_k3_t6', ['mbconv_k7_t6', 'mbconv_k7_t3'], 2, 1]|
[[128, 192], 'mbconv_k7_t6', ['mbconv_k5_t3', 'mbconv_k7_t6', 'mbconv_k7_t6'], 3, 2]|
[[192, 384], 'mbconv_k5_t3', [], 0, 1]|
[[384, 1984], 'conv1_1']
11/19 11:16:15 Total 19 layers.
11/19 11:16:15 Derived Model Mult-Adds = 424.00MB
11/19 11:16:15 Derived Model Num Params = 5.42MB
11/19 11:16:16 epoch 6 weight_lr 1.992126e-01
#######################

It seems normal before it updates the architecture(before epoch 50)
and tends to choose the smallest kernel&ratio after epoch 50.

#######################
11/20 02:14:01 Derived arch: 
[[16, 16], 'mbconv_k3_t1', [], 0, 1]|
[[16, 24], 'mbconv_k3_t3', ['mbconv_k3_t3', 'mbconv_k3_t3', 'mbconv_k3_t3'], 3, 2]|
[[24, 48], 'mbconv_k3_t3', ['mbconv_k3_t3', 'mbconv_k3_t3', 'mbconv_k3_t3'], 3, 2]|
[[48, 72], 'mbconv_k3_t3', ['mbconv_k3_t3', 'mbconv_k3_t3', 'mbconv_k3_t3'], 3, 2]|
[[72, 128], 'mbconv_k3_t3', ['mbconv_k3_t3', 'mbconv_k3_t3', 'mbconv_k3_t3'], 3, 1]|
[[128, 192], 'mbconv_k3_t3', ['mbconv_k3_t3', 'mbconv_k3_t3', 'mbconv_k3_t3'], 3, 2]|
[[192, 384], 'mbconv_k3_t3', [], 0, 1]|
[[384, 1984], 'conv1_1']
11/20 02:14:01 Total 23 layers.
11/20 02:14:01 Derived Model Mult-Adds = 306.19MB
11/20 02:14:01 Derived Model Num Params = 4.46MB
11/20 02:14:02 epoch 54 arch_lr 3.000000e-04
########################

And it almost doesn't change til the end.
I wonder how this phenomenon happens. Hope for your reply!

**Comment by JaminFong** [comment]
Hi, thanks for your interest in our work. Could you please provide the complete searching log file? Thus, I can get detailed information about your running. In addition, how many GPUs do you use in your experiment?

**Comment by mileswyn** [comment]
[log.txt](https://github.com/JaminFong/DenseNAS/files/5677219/log.txt)
I’m so glad you can help me out of this LOL. 
I use only one gpu since I got a bug when I use multi-gpu. I guess maybe it's my pytorch version did not match(I use pytorch 1.7.0/cuda10.2).
Btw, I miss another bug when I run the search script before I got the log file.
That is, in OPTIMIZER.arch_step, I change the parameter 'search_stage' from 2 to 1 in function 'sample_branch', since it return a bug in function 'comp_rescale_value'. And I dont know if this change makes some difference of the derived model.
Thanks a lot!

**Comment by JaminFong** [comment]
Hi! Could please provide all the config details of your experiment, which should have been written into the log file but I didn't find it? In addition, running with a single GPU may cause the batch size too small to support the optimization. And what is the bug you mentioned on `comp_rescale_value`? Manually changing the `sample_branch` parameter may lead to some problems.

**Comment by mileswyn** [comment]
![捕获](https://user-images.githubusercontent.com/59493792/101878135-0ba92880-3bca-11eb-90af-488317133a9e.PNG)
[config.txt](https://github.com/JaminFong/DenseNAS/files/5677839/config.txt)
Hi！Im not sure if these are enough. Please tell me if I miss some important information.

**Comment by mileswyn** [comment]
###############
12/11 15:59:08 epoch 0 arch_lr 3.000000e-04
Traceback (most recent call last):
  File "/hdd1/wyn/DenseNAS/run_apis/search.py", line 158, in <module>
    super_model, epoch, 'Arch', search_stage)
  File "/hdd1/wyn/DenseNAS/run_apis/trainer.py", line 153, in train
    logits, loss, sub_obj = self.search_optim.arch_step(input, target, model, search_stage)
  File "/hdd1/wyn/DenseNAS/run_apis/optimizer.py", line 54, in arch_step
    model)
  File "/hdd1/wyn/DenseNAS/run_apis/optimizer.py", line 113, in rescale_arch_params
    rescale_params(alpha_head_weights_drop, model.module.alpha_head_weights, alpha_head_index)
  File "/hdd1/wyn/DenseNAS/run_apis/optimizer.py", line 109, in rescale_params
    indices_branch)
  File "/hdd1/wyn/DenseNAS/run_apis/optimizer.py", line 100, in comp_rescale_value
    rescale_mat = torch.zeros_like(new_weights).scatter_(0, index, rescale_value)
RuntimeError: Expected index [2] to be smaller than self [6] apart from dimension 0 and to be smaller size than src []

Process finished with exit code 1

###############
[config.txt](https://github.com/JaminFong/DenseNAS/files/5677860/config.txt)

Hi! Im not sure if these are enough. Please tell me if I miss some important information.

**Comment by JaminFong** [comment]
The higher version of PyTorch seems to carry incompatibility issues, as also mentioned in [issues-17](https://github.com/JaminFong/DenseNAS/issues/17). We have tested the code on PyTorch 1.0 - 1.2. Could you have a try with a lower PyTorch version with the defaut parameters, e.g. `search_stage`, not changed, if needed?

**Comment by mileswyn** [comment]
> The higher version of PyTorch seems to carry incompatibility issues, as also mentioned in [issues-17](https://github.com/JaminFong/DenseNAS/issues/17). We have tested the code on PyTorch 1.0 - 1.2. Could you have a try with a lower PyTorch version with the defaut parameters, e.g. `search_stage`, not changed, if needed?

Thx a lot for your kind advice. I'll have a try then!
