### ISSUE TITLE
Sub loss factor in ResNet-based search space

### ISSUE THREAD

**Issue by Debrove** [JaminFong/DenseNAS#19]
Hi, thanks for your great work.

Could you please provide the sub loss factor corresponding to DenseNAS-R1 and DenseNAS-R2 respectively for chained cost estimation. I can not find it in the paper and default value in the code is 0.2.

Thank you.

**Comment by JaminFong** [comment]
Hi, thanks for your attention. `sub_loss_factor` is set as 0.2 for both architectures, but `log_base` is set as 1700 and 3500 for R1 and R2 respectively. 
https://github.com/JaminFong/DenseNAS/blob/e479206f9d73808d4167c669bb1d045a73b6f470/configs/imagenet_search_cfg_resnet.yaml#L63

**Comment by Debrove** [comment]
GOOD! Thanks for your reply.

I search on the ResNet-based search space and so far I have derived an architecture at epoch 54 shown as below:

[[32, 56], 'basic_block', [], 0, 2]|
[[56, 96], 'basic_block', [], 0, 2]|
[[96, 176], 'basic_block', [], 0, 2]|
[[176, 208], 'basic_block', ['basic_block'], 1, 1]|
[[208, 272], 'basic_block', [], 0, 2]|
[[272, 512], 'basic_block', [], 0, 1]

It seems too much skip connections in the basic layers and it is different from the Table 6 in the paper.

The only modification is that the batch size is set to 64 to avoid OOM. So I wonder if the batch size affects the search. 

Could you please help me? And my [log](https://github.com/JaminFong/DenseNAS/files/5770167/log_densenas.txt) is here. Thank you very much.

**Comment by JaminFong** [comment]
Hi, the batch size of 64 is too small. Try with the same size provided.

**Comment by Debrove** [comment]
OK! Thanks for your help!
