### ISSUE TITLE
Could you please tell me something about your strategy

### ISSUE THREAD

**Issue by HONGJUNRL** [JaminFong/DenseNAS#2]
In the traditional darts methods, weights and architecture are optimized step by step, but in your paper, weights and architecture are optimized by epoch, is it mean that in this epoch,the model optimizes weights and in the next epoch, the model optimizes the architecture. I am quite confused.

**Comment by JaminFong** [comment]
> alternate the optimization process of weights and architecture by epoch

It means that we split one search epoch into two parts. We first optimize the operation weights on the training dataset and after that, we optimize the architecture on the validation dataset.

**Comment by HONGJUNRL** [comment]
Thanks for your reply


发自我的iPhone

------------------ Original ------------------
