### ISSUE TITLE
About source code.

### ISSUE THREAD

**Issue by Jack-ouc** [JaminFong/DenseNAS#4]
你好，华科的兄弟，知道你是中国人我就用中文了。我看了源码，感觉你们这个源码只是针对已经搜索好的代码进行训练的对吗，那搜索过程的源码可不可以给我一下呢。

**Comment by JaminFong** [comment]
您好，感谢您的关注。相关代码在整理完成和通过公司审批后，我们会有开源计划，欢迎交流！

**Comment by Jack-ouc** [comment]
嗯呢，可以了解一下代码何时会进行公司审批呢，很想尽快看看搜索的效果，自己也想进行这方面的尝试，如果有源码就省很多功夫了。我现在读研，一个人做这方面的事情，哈哈。

**Comment by JaminFong** [comment]
欢迎关注我们repo的后续更新哦，加油！
