### ISSUE TITLE
net_config

### ISSUE THREAD

**Issue by JacobLau84** [JaminFong/DenseNAS#5]
您好，想请教一下我想要retrain自己的model的话，net_config这个档案要如何生成呢？

感谢。

**Comment by JaminFong** [comment]
您好，如果您的model与DenseNAS model类似（基于MobileNet或ResNet模块等），可以参照提供的net_config自行编写；如若不太合适编写类似的net_config，则可重新定义`retrain.py`中的`model`变量。
https://github.com/JaminFong/DenseNAS/blob/5c3ecbbf2672c3228b9403ff40b64c22b576a919/run_apis/retrain.py#L65
