### ISSUE TITLE
Shape alignement code

### ISSUE THREAD

**Issue by theevann** [JaminFong/DenseNAS#6]
Hi !
I am interested in the **shape-alignement layer** and I would like to know if you could share a snippet of code for this layer ? This part is unfortunately not detailed in the paper.
Thank you much !

**Comment by JaminFong** [comment]
@theevann Hi! Thanks for your attention to our work. The code of the search space is released. The **shape-alignment layer** is defined as `HeadLayer` in the code for simplicity. Hoping this can help you.
https://github.com/JaminFong/DenseNAS/blob/9ed464a8e13f989b7b2a4c7719fbc04febded2fe/models/search_space_base.py#L22
