### ISSUE TITLE
Script for search  

### ISSUE THREAD

**Issue by soyebn** [JaminFong/DenseNAS#7]
In another issue you mentioned "The code of the search space is released." How do I start search process ? Do you have script similar to **run_apis.retrain**? 

Btw I am the same guy who posted a question on your another work, FNA. :-)

**Comment by JaminFong** [comment]
Hi! Thanks for your interest in our work. The total search code will be released in the future. Please pay attention to the repository update if needed.

**Comment by JaminFong** [comment]
@soyebn Hi soyebn! The complete search code is released, hoping this may help you.

**Comment by soyebn** [comment]
Thanks a lot for this.
