### ISSUE TITLE
Preparation of the dataset

### ISSUE THREAD

**Issue by colorjam** [JaminFong/DenseNAS#9]
Hi, thanks for your interesting work.
How do you organize your training data? In folder `imagenet/train` there are sub-folders like `nxxx`. But when using `mk_split_img_list.py`  to split the training data, it may skip the folders as follows:
```
if not os.path.isdir(split_path):
    continue
```

**Comment by JaminFong** [comment]
Hi @colorjam !
Thanks for your interest in our work. The training data is organized as the standard ImageNet, i.e.,
-ImageNet
--train
---nxxx
--val
---nxxx
The non-folder items will be skipped by `if not os.path.isdir(split_path)`. 
> https://github.com/JaminFong/DenseNAS/blob/883bc040704cbcfa6e35b7cc64590e7a44d63565/dataset/mk_split_img_list.py#L8
I name the origin `train` folder as `train_img`, and this may cause some issues in your experiment. I have changed it to `train`.
Thanks a lot for reminding me.

**Comment by colorjam** [comment]
Thanks for your quick reply. I notice that so I close the issue.
